//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.12.17 at 09:43:27 AM GMT+07:00 
//


package com.mvnforum.jaxb.db;


/**
 * Java content class for ThreadType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/working/mvnforum/contrib/phpbb2mvnforum-jaxb/schema/mvnforum.xsd line 180)
 * <p>
 * <pre>
 * &lt;complexType name="ThreadType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MemberName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThreadLastPostMemberName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThreadTopic" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThreadBody" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThreadVoteCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadVoteTotalStars" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadCreationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThreadLastPostDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThreadType" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadOption" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadStatus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadHasPoll" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadViewCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadReplyCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadIcon" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThreadDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ThreadWatchList" type="{}ThreadWatchList" minOccurs="0"/>
 *         &lt;element name="FavoriteThreadList" type="{}FavoriteThreadList" minOccurs="0"/>
 *         &lt;element name="PostList" type="{}PostList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ThreadType {


    /**
     * Gets the value of the threadOption property.
     * 
     */
    int getThreadOption();

    /**
     * Sets the value of the threadOption property.
     * 
     */
    void setThreadOption(int value);

    /**
     * Gets the value of the postList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.PostList}
     */
    com.mvnforum.jaxb.db.PostList getPostList();

    /**
     * Sets the value of the postList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.PostList}
     */
    void setPostList(com.mvnforum.jaxb.db.PostList value);

    /**
     * Gets the value of the threadDuration property.
     * 
     */
    int getThreadDuration();

    /**
     * Sets the value of the threadDuration property.
     * 
     */
    void setThreadDuration(int value);

    /**
     * Gets the value of the threadStatus property.
     * 
     */
    int getThreadStatus();

    /**
     * Sets the value of the threadStatus property.
     * 
     */
    void setThreadStatus(int value);

    /**
     * Gets the value of the threadVoteCount property.
     * 
     */
    int getThreadVoteCount();

    /**
     * Sets the value of the threadVoteCount property.
     * 
     */
    void setThreadVoteCount(int value);

    /**
     * Gets the value of the threadCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThreadCreationDate();

    /**
     * Sets the value of the threadCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThreadCreationDate(java.lang.String value);

    /**
     * Gets the value of the threadVoteTotalStars property.
     * 
     */
    int getThreadVoteTotalStars();

    /**
     * Sets the value of the threadVoteTotalStars property.
     * 
     */
    void setThreadVoteTotalStars(int value);

    /**
     * Gets the value of the threadHasPoll property.
     * 
     */
    int getThreadHasPoll();

    /**
     * Sets the value of the threadHasPoll property.
     * 
     */
    void setThreadHasPoll(int value);

    /**
     * Gets the value of the threadReplyCount property.
     * 
     */
    int getThreadReplyCount();

    /**
     * Sets the value of the threadReplyCount property.
     * 
     */
    void setThreadReplyCount(int value);

    /**
     * Gets the value of the threadLastPostDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThreadLastPostDate();

    /**
     * Sets the value of the threadLastPostDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThreadLastPostDate(java.lang.String value);

    /**
     * Gets the value of the threadBody property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThreadBody();

    /**
     * Sets the value of the threadBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThreadBody(java.lang.String value);

    /**
     * Gets the value of the memberName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMemberName();

    /**
     * Sets the value of the memberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMemberName(java.lang.String value);

    /**
     * Gets the value of the threadLastPostMemberName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThreadLastPostMemberName();

    /**
     * Sets the value of the threadLastPostMemberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThreadLastPostMemberName(java.lang.String value);

    /**
     * Gets the value of the threadTopic property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThreadTopic();

    /**
     * Sets the value of the threadTopic property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThreadTopic(java.lang.String value);

    /**
     * Gets the value of the favoriteThreadList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.FavoriteThreadList}
     */
    com.mvnforum.jaxb.db.FavoriteThreadList getFavoriteThreadList();

    /**
     * Sets the value of the favoriteThreadList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.FavoriteThreadList}
     */
    void setFavoriteThreadList(com.mvnforum.jaxb.db.FavoriteThreadList value);

    /**
     * Gets the value of the threadType property.
     * 
     */
    int getThreadType();

    /**
     * Sets the value of the threadType property.
     * 
     */
    void setThreadType(int value);

    /**
     * Gets the value of the threadIcon property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getThreadIcon();

    /**
     * Sets the value of the threadIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setThreadIcon(java.lang.String value);

    /**
     * Gets the value of the threadWatchList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.ThreadWatchList}
     */
    com.mvnforum.jaxb.db.ThreadWatchList getThreadWatchList();

    /**
     * Sets the value of the threadWatchList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.ThreadWatchList}
     */
    void setThreadWatchList(com.mvnforum.jaxb.db.ThreadWatchList value);

    /**
     * Gets the value of the threadViewCount property.
     * 
     */
    int getThreadViewCount();

    /**
     * Sets the value of the threadViewCount property.
     * 
     */
    void setThreadViewCount(int value);

}
