//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.12.17 at 09:43:27 AM GMT+07:00 
//


package com.mvnforum.jaxb.db;


/**
 * Java content class for ForumType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/D:/working/mvnforum/contrib/phpbb2mvnforum-jaxb/schema/mvnforum.xsd line 118)
 * <p>
 * <pre>
 * &lt;complexType name="ForumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ForumLastPostMemberName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForumName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ForumDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForumCreationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForumModifiedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForumLastPostDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForumOrder" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumType" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumFormatOption" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumOption" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumStatus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumModerationMode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ForumThreadCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ForumPostCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MemberForumPermissionList" type="{}MemberForumPermissionList" minOccurs="0"/>
 *         &lt;element name="GroupForumPermissionList" type="{}GroupForumPermissionList" minOccurs="0"/>
 *         &lt;element name="ForumWatchList" type="{}ForumWatchList" minOccurs="0"/>
 *         &lt;element name="ThreadList" type="{}ThreadList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ForumType {


    /**
     * Gets the value of the forumLastPostMemberName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumLastPostMemberName();

    /**
     * Sets the value of the forumLastPostMemberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumLastPostMemberName(java.lang.String value);

    /**
     * Gets the value of the forumPassword property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumPassword();

    /**
     * Sets the value of the forumPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumPassword(java.lang.String value);

    /**
     * Gets the value of the forumType property.
     * 
     */
    int getForumType();

    /**
     * Sets the value of the forumType property.
     * 
     */
    void setForumType(int value);

    /**
     * Gets the value of the forumModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumModifiedDate();

    /**
     * Sets the value of the forumModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumModifiedDate(java.lang.String value);

    /**
     * Gets the value of the forumOption property.
     * 
     */
    int getForumOption();

    /**
     * Sets the value of the forumOption property.
     * 
     */
    void setForumOption(int value);

    /**
     * Gets the value of the memberForumPermissionList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.MemberForumPermissionList}
     */
    com.mvnforum.jaxb.db.MemberForumPermissionList getMemberForumPermissionList();

    /**
     * Sets the value of the memberForumPermissionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.MemberForumPermissionList}
     */
    void setMemberForumPermissionList(com.mvnforum.jaxb.db.MemberForumPermissionList value);

    /**
     * Gets the value of the forumStatus property.
     * 
     */
    int getForumStatus();

    /**
     * Sets the value of the forumStatus property.
     * 
     */
    void setForumStatus(int value);

    /**
     * Gets the value of the forumDesc property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumDesc();

    /**
     * Sets the value of the forumDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumDesc(java.lang.String value);

    /**
     * Gets the value of the groupForumPermissionList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.GroupForumPermissionList}
     */
    com.mvnforum.jaxb.db.GroupForumPermissionList getGroupForumPermissionList();

    /**
     * Sets the value of the groupForumPermissionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.GroupForumPermissionList}
     */
    void setGroupForumPermissionList(com.mvnforum.jaxb.db.GroupForumPermissionList value);

    /**
     * Gets the value of the forumCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumCreationDate();

    /**
     * Sets the value of the forumCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumCreationDate(java.lang.String value);

    /**
     * Gets the value of the forumPostCount property.
     * 
     */
    int getForumPostCount();

    /**
     * Sets the value of the forumPostCount property.
     * 
     */
    void setForumPostCount(int value);

    /**
     * Gets the value of the forumOrder property.
     * 
     */
    int getForumOrder();

    /**
     * Sets the value of the forumOrder property.
     * 
     */
    void setForumOrder(int value);

    /**
     * Gets the value of the forumFormatOption property.
     * 
     */
    int getForumFormatOption();

    /**
     * Sets the value of the forumFormatOption property.
     * 
     */
    void setForumFormatOption(int value);

    /**
     * Gets the value of the forumWatchList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.ForumWatchList}
     */
    com.mvnforum.jaxb.db.ForumWatchList getForumWatchList();

    /**
     * Sets the value of the forumWatchList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.ForumWatchList}
     */
    void setForumWatchList(com.mvnforum.jaxb.db.ForumWatchList value);

    /**
     * Gets the value of the forumName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumName();

    /**
     * Sets the value of the forumName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumName(java.lang.String value);

    /**
     * Gets the value of the forumModerationMode property.
     * 
     */
    int getForumModerationMode();

    /**
     * Sets the value of the forumModerationMode property.
     * 
     */
    void setForumModerationMode(int value);

    /**
     * Gets the value of the threadList property.
     * 
     * @return
     *     possible object is
     *     {@link com.mvnforum.jaxb.db.ThreadList}
     */
    com.mvnforum.jaxb.db.ThreadList getThreadList();

    /**
     * Sets the value of the threadList property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.mvnforum.jaxb.db.ThreadList}
     */
    void setThreadList(com.mvnforum.jaxb.db.ThreadList value);

    /**
     * Gets the value of the forumLastPostDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getForumLastPostDate();

    /**
     * Sets the value of the forumLastPostDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setForumLastPostDate(java.lang.String value);

    /**
     * Gets the value of the forumThreadCount property.
     * 
     */
    int getForumThreadCount();

    /**
     * Sets the value of the forumThreadCount property.
     * 
     */
    void setForumThreadCount(int value);

}
