/*
 * $Header: /cvsroot/mvnforum/mvnforum/contrib/phpbb2mvnforum/src/org/mvnforum/phpbb2mvnforum/db/PhpbbUsers.java,v 1.4 2007/01/15 10:27:32 dungbtm Exp $
 * $Author: dungbtm $
 * $Revision: 1.4 $
 * $Date: 2007/01/15 10:27:32 $
 *
 * ====================================================================
 *
 * Copyright (C) 2002-2007 by MyVietnam.net
 *
 * All copyright notices regarding mvnForum MUST remain 
 * intact in the scripts and in the outputted HTML.
 * The "powered by" text/logo with a link back to
 * http://www.mvnForum.com and http://www.MyVietnam.net in 
 * the footer of the pages MUST remain visible when the pages
 * are viewed on the internet or intranet.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Support can be obtained from support forums at:
 * http://www.mvnForum.com/mvnforum/index
 *
 * Correspondence and Marketing Questions can be sent to:
 * info at MyVietnam net
 *
 * @author: 
 */
package org.mvnforum.phpbb2mvnforum.db;

import java.math.BigDecimal;

/**
 * PhpbbUsers generated by hbm2java
 */
public class PhpbbUsers implements java.io.Serializable {

    // Fields    

    private int userId;

    private int userActive;

    private String username;

    private String userPassword;

    private long userSessionTime;

    private int userSessionPage;

    private long userLastvisit;

    private long userRegdate;

    private int userLevel;

    private int userPosts;

    private BigDecimal userTimezone;

    private int userStyle;

    private String userLang;

    private String userDateformat;

    private int userNewPrivmsg;

    private int userUnreadPrivmsg;

    private long userLastPrivmsg;

    private int userEmailtime;

    private int userViewemail;

    private int userAttachsig;

    private int userAllowhtml;

    private int userAllowbbcode;

    private int userAllowsmile;

    private int userAllowavatar;

    private int userAllowPm;

    private int userAllowViewonline;

    private int userNotify;

    private int userNotifyPm;

    private int userPopupPm;

    private int userRank;

    private String userAvatar;

    private int userAvatarType;

    private String userEmail;

    private String userIcq;

    private String userWebsite;

    private String userFrom;

    private String userSig;

    private String userSigBbcodeUid;

    private String userAim;

    private String userYim;

    private String userMsnm;

    private String userOcc;

    private String userInterests;

    private String userActkey;

    private String userNewpasswd;

    // Constructors

    /** default constructor */
    public PhpbbUsers() {
    }

    public int getUserActive() {
        return userActive;
    }

    public void setUserActive(int userActive) {
        this.userActive = userActive;
    }

    public String getUserActkey() {
        return userActkey;
    }

    public void setUserActkey(String userActkey) {
        this.userActkey = userActkey;
    }

    public String getUserAim() {
        return userAim;
    }

    public void setUserAim(String userAim) {
        this.userAim = userAim;
    }

    public int getUserAllowavatar() {
        return userAllowavatar;
    }

    public void setUserAllowavatar(int userAllowavatar) {
        this.userAllowavatar = userAllowavatar;
    }

    public int getUserAllowbbcode() {
        return userAllowbbcode;
    }

    public void setUserAllowbbcode(int userAllowbbcode) {
        this.userAllowbbcode = userAllowbbcode;
    }

    public int getUserAllowhtml() {
        return userAllowhtml;
    }

    public void setUserAllowhtml(int userAllowhtml) {
        this.userAllowhtml = userAllowhtml;
    }

    public int getUserAllowPm() {
        return userAllowPm;
    }

    public void setUserAllowPm(int userAllowPm) {
        this.userAllowPm = userAllowPm;
    }

    public int getUserAllowsmile() {
        return userAllowsmile;
    }

    public void setUserAllowsmile(int userAllowsmile) {
        this.userAllowsmile = userAllowsmile;
    }

    public int getUserAllowViewonline() {
        return userAllowViewonline;
    }

    public void setUserAllowViewonline(int userAllowViewonline) {
        this.userAllowViewonline = userAllowViewonline;
    }

    public int getUserAttachsig() {
        return userAttachsig;
    }

    public void setUserAttachsig(int userAttachsig) {
        this.userAttachsig = userAttachsig;
    }

    public String getUserAvatar() {
        return userAvatar;
    }

    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    public int getUserAvatarType() {
        return userAvatarType;
    }

    public void setUserAvatarType(int userAvatarType) {
        this.userAvatarType = userAvatarType;
    }

    public String getUserDateformat() {
        return userDateformat;
    }

    public void setUserDateformat(String userDateformat) {
        this.userDateformat = userDateformat;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public int getUserEmailtime() {
        return userEmailtime;
    }

    public void setUserEmailtime(int userEmailtime) {
        this.userEmailtime = userEmailtime;
    }

    public String getUserFrom() {
        return userFrom;
    }

    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom;
    }

    public String getUserIcq() {
        return userIcq;
    }

    public void setUserIcq(String userIcq) {
        this.userIcq = userIcq;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUserInterests() {
        return userInterests;
    }

    public void setUserInterests(String userInterests) {
        this.userInterests = userInterests;
    }

    public String getUserLang() {
        return userLang;
    }

    public void setUserLang(String userLang) {
        this.userLang = userLang;
    }

    public long getUserLastPrivmsg() {
        return userLastPrivmsg;
    }

    public void setUserLastPrivmsg(long userLastPrivmsg) {
        this.userLastPrivmsg = userLastPrivmsg;
    }

    public long getUserLastvisit() {
        return userLastvisit;
    }

    public void setUserLastvisit(long userLastvisit) {
        this.userLastvisit = userLastvisit;
    }

    public int getUserLevel() {
        return userLevel;
    }

    public void setUserLevel(int userLevel) {
        this.userLevel = userLevel;
    }

    public String getUserMsnm() {
        return userMsnm;
    }

    public void setUserMsnm(String userMsnm) {
        this.userMsnm = userMsnm;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserNewpasswd() {
        return userNewpasswd;
    }

    public void setUserNewpasswd(String userNewpasswd) {
        this.userNewpasswd = userNewpasswd;
    }

    public int getUserNewPrivmsg() {
        return userNewPrivmsg;
    }

    public void setUserNewPrivmsg(int userNewPrivmsg) {
        this.userNewPrivmsg = userNewPrivmsg;
    }

    public int getUserNotify() {
        return userNotify;
    }

    public void setUserNotify(int userNotify) {
        this.userNotify = userNotify;
    }

    public int getUserNotifyPm() {
        return userNotifyPm;
    }

    public void setUserNotifyPm(int userNotifyPm) {
        this.userNotifyPm = userNotifyPm;
    }

    public String getUserOcc() {
        return userOcc;
    }

    public void setUserOcc(String userOcc) {
        this.userOcc = userOcc;
    }

    public String getUserPassword() {
        return userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public int getUserPopupPm() {
        return userPopupPm;
    }

    public void setUserPopupPm(int userPopupPm) {
        this.userPopupPm = userPopupPm;
    }

    public int getUserPosts() {
        return userPosts;
    }

    public void setUserPosts(int userPosts) {
        this.userPosts = userPosts;
    }

    public int getUserRank() {
        return userRank;
    }

    public void setUserRank(int userRank) {
        this.userRank = userRank;
    }

    

    public int getUserSessionPage() {
        return userSessionPage;
    }

    public void setUserSessionPage(int userSessionPage) {
        this.userSessionPage = userSessionPage;
    }

    public long getUserSessionTime() {
        return userSessionTime;
    }

    public void setUserSessionTime(long userSessionTime) {
        this.userSessionTime = userSessionTime;
    }

    public String getUserSig() {
        return userSig;
    }

    public void setUserSig(String userSig) {
        this.userSig = userSig;
    }

    public String getUserSigBbcodeUid() {
        return userSigBbcodeUid;
    }

    public void setUserSigBbcodeUid(String userSigBbcodeUid) {
        this.userSigBbcodeUid = userSigBbcodeUid;
    }

    public int getUserStyle() {
        return userStyle;
    }

    public void setUserStyle(int userStyle) {
        this.userStyle = userStyle;
    }

    public BigDecimal getUserTimezone() {
        return userTimezone;
    }

    public void setUserTimezone(BigDecimal userTimezone) {
        this.userTimezone = userTimezone;
    }

    public int getUserUnreadPrivmsg() {
        return userUnreadPrivmsg;
    }

    public void setUserUnreadPrivmsg(int userUnreadPrivmsg) {
        this.userUnreadPrivmsg = userUnreadPrivmsg;
    }

    public int getUserViewemail() {
        return userViewemail;
    }

    public void setUserViewemail(int userViewemail) {
        this.userViewemail = userViewemail;
    }

    public String getUserWebsite() {
        return userWebsite;
    }

    public void setUserWebsite(String userWebsite) {
        this.userWebsite = userWebsite;
    }

    public String getUserYim() {
        return userYim;
    }

    public void setUserYim(String userYim) {
        this.userYim = userYim;
    }

    public long getUserRegdate() {
        return userRegdate;
    }

    public void setUserRegdate(long userRegdate) {
        this.userRegdate = userRegdate;
    }

}